name: wxregimes
channels:
  - conda-forge        
dependencies:
  - python=3.6
  - jupyterlab
  - jupyter_client
  - nbserverproxy
  - netcdf4
  - numpy
  - cfgrib
  - scipy
  - xarray
  - dask
  - cartopy
  - matplotlib
  - cartopy
  - ipywidgets
  - eofs

